services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 5g
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis:
  ollama_data:
