import { createTicket } from "@/api/tickets";
import { api, mockDelay, USE_MOCK } from "@/api/client";
import type { Ticket } from "@/types";

export async function seedTickets(count: number): Promise<{ count: number }> {
  if (USE_MOCK) return mockDelay({ count });
  const { data } = await api.post<{ count: number }>("/simulator/seed", { count });
  return data;
}

export async function startSimulator(): Promise<{ started: boolean }> {
  if (USE_MOCK) return mockDelay({ started: true });
  const { data } = await api.post<{ started: boolean }>("/simulator/start");
  return data;
}

export async function stopSimulator(): Promise<{ stopped: boolean }> {
  if (USE_MOCK) return mockDelay({ stopped: true });
  const { data } = await api.post<{ stopped: boolean }>("/simulator/stop");
  return data;
}

export async function randomTicket(): Promise<Ticket> {
  if (USE_MOCK) {
    return createTicket({
      customerEmail: `random${Date.now()}@example.com`,
      subject: "Random simulated customer issue",
      message: "Generated by the simulator to exercise the support processing pipeline.",
    });
  }
  const { data } = await api.post<Ticket>("/simulator/random-ticket");
  return data;
}

export async function forceFailure(): Promise<Ticket> {
  if (USE_MOCK) {
    const ticket = await randomTicket();
    ticket.status = "FAILED";
    ticket.errorMessage = "Forced simulator failure";
    return ticket;
  }
  const { data } = await api.post<Ticket>("/simulator/force-failure");
  return data;
}
